# Primon Proto 
# Headless WebSocket, type-safe Whatsapp UserBot
# 
# Primon, lisanced under GNU GENERAL PUBLIC LICENSE. May cause some warranity problems, within Priomon.
# Multi-Device Lightweight ES5 Module (can ysable with mjs)
#
# Phaticusthiccy - 2022


ARG EnvironmentVariable
RAILWAY_DOCKERFILE_PATH = Dockerfile.origin